In [67]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split  
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
dataset = load_digits()

In [5]:
dir(dataset)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [28]:
X_train, X_test, y_train, y_test = train_test_split(dataset.data, dataset.target, test_size = 0.3)
print(len(dataset.target))

1797


In [14]:
a = LogisticRegression()
a.fit(X_train, y_train)
a.score(X_test, y_test)

/Users/spaceconsole/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [15]:
b = SVC()
b.fit(X_train, y_train)
b.score(X_test, y_test)

0.9851851851851852

In [16]:
c = RandomForestClassifier()
c.fit(X_train, y_train)
c.score(X_test, y_test)

0.9740740740740741

In [50]:
fold = StratifiedKFold(n_splits = 10)

In [31]:
def scores(model, X_train, y_train, X_test, y_test, lst):
    model.fit(X_train, y_train)
    lst.append(model.score(X_test, y_test))

In [57]:
aa = []
ba = []
ca = []
for train_index, test_index in fold.split(dataset.data, dataset.target):
    X_train, y_train, X_test, y_test = dataset.data[train_index], dataset.target[train_index], dataset.data[test_index], dataset.target[test_index]
    scores(LogisticRegression(), X_train, y_train, X_test, y_test, aa)
    scores(SVC(), X_train, y_train, X_test, y_test, ba)
    scores(RandomForestClassifier(n_estimators = 50), X_train, y_train, X_test, y_test, ca)

/Users/spaceconsole/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/spaceconsole/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.ht

In [63]:
print("Softmax Regression:", aa)

Softmax Regression: [0.9055555555555556, 0.9611111111111111, 0.8777777777777778, 0.9277777777777778, 0.9444444444444444, 0.9666666666666667, 0.95, 0.9385474860335196, 0.8715083798882681, 0.9385474860335196]


In [65]:
print("SVM:", ba)

SVM: [0.9444444444444444, 0.9888888888888889, 0.9277777777777778, 0.9666666666666667, 0.9833333333333333, 0.9888888888888889, 0.9888888888888889, 0.994413407821229, 0.9608938547486033, 0.9553072625698324]


In [64]:
print("Random Forest:", ca)

Random Forest: [0.9111111111111111, 0.9666666666666667, 0.9222222222222223, 0.9333333333333333, 0.9611111111111111, 0.9666666666666667, 0.9722222222222222, 0.9608938547486033, 0.9385474860335196, 0.9329608938547486]


In [69]:
cross_val_score(LogisticRegression(), dataset.data, dataset.target)

/Users/spaceconsole/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/spaceconsole/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.ht

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [71]:
cross_val_score(SVC(), dataset.data, dataset.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [73]:
cross_val_score(RandomForestClassifier(), dataset.data, dataset.target)

array([0.93333333, 0.90555556, 0.95821727, 0.9637883 , 0.92200557])