In [72]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

In [57]:
iris = load_iris()
df = pd.DataFrame(data = iris.data, columns = iris.feature_names) 
df['target'] = [i for i in iris.target]
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
145       2  
146       2  
147       2  
148       2  
149       2

In [59]:
X = df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']]
Y = df['target']

In [60]:
y = Y.to_numpy()

In [61]:
def one_hot_encoding(y):
    col = np.unique(y).shape[0]
    encode = np.zeros((y.shape[0], col))
    for idx, val in enumerate(y):
        encode[idx][val] = 1
    return encode

In [70]:
y_encode = one_hot_encoding(y)
x = X.to_numpy()

In [90]:
model = LogisticRegression()
model.fit(pd.DataFrame(x), pd.Series(y))

/Users/spaceconsole/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [89]:
y_pred = model.predict(pd.DataFrame(x))
model.score(pd.DataFrame(X), pd.Series(y))

/Users/spaceconsole/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


0.9733333333333334

In [92]:
model.predict(pd.DataFrame(x))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [95]:
print(model.coef_.T, model.intercept_)

[[-0.41887908  0.53127466 -0.11239558]
 [ 0.96710627 -0.31479241 -0.65231386]
 [-2.52093331 -0.20020997  2.72114328]
 [-1.08419917 -0.94850676  2.03270594]] [  9.8405634    2.21733979 -12.05790319]
